/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CellColor, CellData, CellMode } from "./extra/types";
export namespace Components {
    interface CodenamesApp {
    }
    interface CodenamesBoard {
        /**
          * Data list used to generate the cells.
         */
        "cellData"?: CellData;
    }
    interface CodenamesCell {
        /**
          * Cell color.
         */
        "color": CellColor;
        /**
          * Cell display mode.
         */
        "mode": CellMode;
        /**
          * Whether the cell is revealed.
         */
        "revealed": boolean;
        /**
          * Word shown in cell.
         */
        "word": string;
    }
}
declare global {
    interface HTMLCodenamesAppElement extends Components.CodenamesApp, HTMLStencilElement {
    }
    var HTMLCodenamesAppElement: {
        prototype: HTMLCodenamesAppElement;
        new (): HTMLCodenamesAppElement;
    };
    interface HTMLCodenamesBoardElement extends Components.CodenamesBoard, HTMLStencilElement {
    }
    var HTMLCodenamesBoardElement: {
        prototype: HTMLCodenamesBoardElement;
        new (): HTMLCodenamesBoardElement;
    };
    interface HTMLCodenamesCellElement extends Components.CodenamesCell, HTMLStencilElement {
    }
    var HTMLCodenamesCellElement: {
        prototype: HTMLCodenamesCellElement;
        new (): HTMLCodenamesCellElement;
    };
    interface HTMLElementTagNameMap {
        "codenames-app": HTMLCodenamesAppElement;
        "codenames-board": HTMLCodenamesBoardElement;
        "codenames-cell": HTMLCodenamesCellElement;
    }
}
declare namespace LocalJSX {
    interface CodenamesApp {
    }
    interface CodenamesBoard {
        /**
          * Data list used to generate the cells.
         */
        "cellData"?: CellData;
    }
    interface CodenamesCell {
        /**
          * Cell color.
         */
        "color"?: CellColor;
        /**
          * Cell display mode.
         */
        "mode"?: CellMode;
        /**
          * Whether the cell is revealed.
         */
        "revealed"?: boolean;
        /**
          * Word shown in cell.
         */
        "word"?: string;
    }
    interface IntrinsicElements {
        "codenames-app": CodenamesApp;
        "codenames-board": CodenamesBoard;
        "codenames-cell": CodenamesCell;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "codenames-app": LocalJSX.CodenamesApp & JSXBase.HTMLAttributes<HTMLCodenamesAppElement>;
            "codenames-board": LocalJSX.CodenamesBoard & JSXBase.HTMLAttributes<HTMLCodenamesBoardElement>;
            "codenames-cell": LocalJSX.CodenamesCell & JSXBase.HTMLAttributes<HTMLCodenamesCellElement>;
        }
    }
}
